# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DotDagger < Formula
  desc "Dotfiles manager — env resolution, DAG, symlinks, and packages"
  homepage "https://github.com/rocne/dot-dagger"
  version "0.2.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.2.21/dotd_v0.2.21_darwin_amd64.tar.gz"
      sha256 "909eadd93a7a6ca7f7314906f3b1037a4d3b783ecce7718dcf421145b1e4b383"

      define_method(:install) do
        bin.install "dotd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.2.21/dotd_v0.2.21_darwin_arm64.tar.gz"
      sha256 "7f0ead2d5610b64aae8cbb13cc50bd632929f8534de1f4b648cf7f9f1bfe1027"

      define_method(:install) do
        bin.install "dotd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.2.21/dotd_v0.2.21_linux_amd64.tar.gz"
      sha256 "911103994206302ab7f11bff3708fc621a9c4151c3ada8bdb8eabb78de4222e6"
      define_method(:install) do
        bin.install "dotd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.2.21/dotd_v0.2.21_linux_arm64.tar.gz"
      sha256 "509cf310419e7675b68adfd00ef8a00855f1b3ea5765d09c07bbf80481fae538"
      define_method(:install) do
        bin.install "dotd"
      end
    end
  end

  test do
    system "#{bin}/dotd", "--version"
  end
end
