# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DotDagger < Formula
  desc "Dotfiles manager — env resolution, DAG, symlinks, and packages"
  homepage "https://github.com/rocne/dot-dagger"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.3.2/dotd_v0.3.2_darwin_amd64.tar.gz"
      sha256 "65ad3dd72a51543d63141f3a512981b5199029362328842f69107b2dfe5d9031"

      define_method(:install) do
        bin.install "dotd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.3.2/dotd_v0.3.2_darwin_arm64.tar.gz"
      sha256 "c21f2cfca61fe0b35b20897c60b10d17e58bc681055ce4dbabc1ccf2a185b40c"

      define_method(:install) do
        bin.install "dotd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.3.2/dotd_v0.3.2_linux_amd64.tar.gz"
      sha256 "117545ebe65ce37359a5ee98cb0d89897cd6e8eb20ee43ecf74fa5eb94e97d83"
      define_method(:install) do
        bin.install "dotd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.3.2/dotd_v0.3.2_linux_arm64.tar.gz"
      sha256 "6fc041a99bb2501525f6520a14769dcb8d7844611ae684c7f5c27b1b7dc94596"
      define_method(:install) do
        bin.install "dotd"
      end
    end
  end

  test do
    system "#{bin}/dotd", "--version"
  end
end
