# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotd < Formula
  desc "Dotfiles manager — env resolution, DAG, symlinks, and packages"
  homepage "https://github.com/rocne/dot-dagger"
  version "0.2.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.2.12/dotd_v0.2.12_darwin_amd64.tar.gz"
      sha256 "da9e447624d7e3477e0791b1a6f7c1576851b1feb763386f5067f3dc7bd48b3d"

      define_method(:install) do
        bin.install "dotd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.2.12/dotd_v0.2.12_darwin_arm64.tar.gz"
      sha256 "bcf775c9b275e0d35521ea780804c1cc70d0d1d27d0e4fcc9ac8ea98e1961fd2"

      define_method(:install) do
        bin.install "dotd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.2.12/dotd_v0.2.12_linux_amd64.tar.gz"
      sha256 "e9fc6b6c7ce1153b58b74f93be580afadc3cb02ed88ffe7f60d7577e18476bc9"
      define_method(:install) do
        bin.install "dotd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rocne/dot-dagger/releases/download/v0.2.12/dotd_v0.2.12_linux_arm64.tar.gz"
      sha256 "9ba79d8ff7c192f2553c9a1cbd48a463e1469b9ca36a30e2e02b475e9ab52115"
      define_method(:install) do
        bin.install "dotd"
      end
    end
  end

  test do
    system "#{bin}/dotd", "--version"
  end
end
