# This file was generated by GoReleaser. DO NOT EDIT.
cask "dot-dagger" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "3a2910fd77889185c373c722ed5d2cd54635d257cf25b19d88dca17b5f02580f"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6da7f73218c5aa6c60e3de806c1ad08bafe24436a370aedbb3df7bceedc38118"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee20bd034ae2cb30e7081fcae3ef9afae27c88884f0ed8269770b530ffca5f85"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "78ee7c8ac9414ef058b4719e664ae6c4cda9cbea5d676064c7c62e66166b5abf"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "dot-dagger"
  desc "Dotfiles manager — env resolution, DAG, symlinks, and packages"
  homepage "https://github.com/rocne/dot-dagger"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dot-dagger"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotd"]
    end
  end

  # No zap stanza required

end
