# This file was generated by GoReleaser. DO NOT EDIT.
cask "dot-dagger" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "026c8b033e83a176e2f583bd5f2c4c9d7f3ca55365e0076aa4d7ed2f42a2c48a"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f45461d0b25da5645e0561c410e882c40dd8b11864c48930bcff3844bc51676"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88a828c5f666bcd543787425936e37851d0e2f27a681f90e62dd7680af89377e"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "530faed014efe1aa4e08f81486865ecb09992e5c8b1b9824917462d57e43da50"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "dot-dagger"
  desc "Dotfiles manager — env resolution, DAG, symlinks, and packages"
  homepage "https://github.com/rocne/dot-dagger"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dot-dagger"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotd"]
    end
  end

  # No zap stanza required

end
