# This file was generated by GoReleaser. DO NOT EDIT.
cask "dot-dagger" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "7367a73391d3d83b7c4b97831adce67c069e4953645384ca5c7c433aa6e9b822"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bda5a69ab10e8826d3a48606be071e38cfba7ed161e1491813970b9fc525f31"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "152f169738156f9a9aaa94fb83913a820291737cce50c0dd23c2378981dbcdd2"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a180c0ff94da593cc894cac4fd513da6e64bf8408f85e7bdff4aaa73dfe6bfcd"
      url "https://github.com/rocne/dot-dagger/releases/download/v#{version}/dotd_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "dot-dagger"
  desc "Dotfiles manager — env resolution, DAG, symlinks, and packages"
  homepage "https://github.com/rocne/dot-dagger"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dot-dagger"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotd"]
    end
  end

  # No zap stanza required

end
