# This file was generated by GoReleaser. DO NOT EDIT.
cask "dstow" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "9f4f6556757eac271abec1cf0e820fbe69412f90a2dd7fef0952ba5c2d10abae"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8a79f0a2be7458d0396776b7166aaeb1f5f14c1dd391cb55587afcb9a2193d2d"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "871eb406f0fd973aae832601407166139783a7a50ebf2cd87bd62849fac221eb"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a8966f76f6ba9bdbd714f5f2d9569a7f5d3b9ddc5a940bc00b033ae51ec1bdef"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "dstow"
  desc "Dotfiles manager built on the gostow engine"
  homepage "https://github.com/rocne/dstow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dstow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dstow"]
    end
  end

  # No zap stanza required

end
