# This file was generated by GoReleaser. DO NOT EDIT.
cask "dstow" do
  version "0.6.2"

  on_macos do
    on_intel do
      sha256 "5d7e9b84f58a1e4a6e42ad2ad08409d81c941dfa488a1f7ee56c70a7b4f942ba"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b552f4a34983890683c5eee5416ed6c8dc8edc1d07bf81548d6f855abe41aa1"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4641727d15ba3c5cf8dee385829e1a8298efcb8ffdbf07694c984eb6bcdfeb78"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6778bebdce9575bc2a3db9e21b76d4dd8f2674c580c803851a598adc57b21087"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "dstow"
  desc "Dotfiles manager built on the gostow engine"
  homepage "https://github.com/rocne/dstow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dstow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dstow"]
    end
  end

  # No zap stanza required

end
