# This file was generated by GoReleaser. DO NOT EDIT.
cask "dstow" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "336491b680084fd3cf481e680f840632a44b520dde3350374d666755a92d8e2d"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ac4b0995af47e27baca5883723c6012dcbb67258db7355d500ebc45c26cbc9e"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb87d71ad2c02e2d594e59273d18d5de0893b839cb5a9aa7d72f439a02a3cc45"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ebb92643c78479802be7549c5705e296eb2542a8ec6358eb50de894f96a2e55"
      url "https://github.com/rocne/dstow/releases/download/v#{version}/dstow_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "dstow"
  desc "Dotfiles manager built on the gostow engine"
  homepage "https://github.com/rocne/dstow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dstow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dstow"]
    end
  end

  # No zap stanza required

end
