# This file was generated by GoReleaser. DO NOT EDIT.
cask "gostow" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "514d29c544aa6a420f5841e0d9206f2561bcf3bc95d2d9f2003959ab26596ab8"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aeb38009d41f0dd7a09a39436a0d0dbd8f195a6485d0ceb5d8a0e685d0e5bc66"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b7cd5c978a4a686489d6c6b302a5f69156e8ec7c3a52c5b1f5fe774c3576ba1"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "67f63821e1a2ab560bfa0cb1c0c004aa599ebfa6f56e7d9890d515812b8bae81"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "gostow"
  desc "GNU Stow, reimplemented in Go — a single static binary, no Perl"
  homepage "https://github.com/rocne/gostow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gostow"
  manpage "man/gostow.8"
  bash_completion "completions/gostow.bash"
  fish_completion "completions/gostow.fish"
  zsh_completion "completions/_gostow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gostow"]
    end
  end

  # No zap stanza required

end
