# This file was generated by GoReleaser. DO NOT EDIT.
cask "gostow" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7e19c707b2237dd09b8b2cb5da7776c14d288632fa563384d28bca63a18a8132"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2bd0add986fdc74703f2203634363deec56624e9e56e6af12527681a7d3c5e7f"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41f90f0002ff501a84d61a2c1cafb69283025bf2dcb5939da5b82e5cfb664729"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bee31066a2de394f9c858a934db26266e1c5c218bf9323c9c3ea06396d71971f"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "gostow"
  desc "GNU Stow, reimplemented in Go — a single static binary, no Perl"
  homepage "https://github.com/rocne/gostow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gostow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gostow"]
    end
  end

  # No zap stanza required

end
