# This file was generated by GoReleaser. DO NOT EDIT.
cask "gostow" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2fd9590d50802a0db12bea45dce58e34cb1caa977921eb4914e1568c75c8fb8f"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dce795938f9f48b1716c51938647cff7e2d14f093bec03468dfd63727603ac5a"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7480c749fd6997d5d279415098d511d0300758b198c6b363dca2fe2a8824164e"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c300bdc6b87b8845cf071a2646eed26c85ed48a9f0167f923c148d3d42c72433"
      url "https://github.com/rocne/gostow/releases/download/v#{version}/gostow_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "gostow"
  desc "GNU Stow, reimplemented in Go — a single static binary, no Perl"
  homepage "https://github.com/rocne/gostow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gostow"
  manpage "man/gostow.8"
  bash_completion "completions/gostow.bash"
  fish_completion "completions/gostow.fish"
  zsh_completion "completions/_gostow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gostow"]
    end
  end

  # No zap stanza required

end
